### ISSUE TITLE
trigger options for create-base and update in pipeline

### ISSUE THREAD

**Issue by bottkars** [cloudfoundry-community/windows-stemcell-concourse#19]
base create should have a on-time trigger
update should have a trygerr on windows updates / new stemcell releases

**Comment by sneal** [comment]
I strongly believe we should avoid online dependencies and work towards supporting offline building of stemcells as a 1st class citizen. See #2

**Comment by ddieruf** [comment]
This was because ok a bug PKS 1.5 and stemcell versions. It was fixed in PKS 1.6. We're all good.
