### ISSUE TITLE
Instructions for air gapped environments

### ISSUE THREAD

**Issue by tezizzm** [cloudfoundry-community/windows-stemcell-concourse#2]
This solution will be valuable to many that are in air gapped environments. 

Provide instructions and/or a list of resources that need to be moved into the environment to allow this solution to be utilized in an air gapped environments.

**Comment by ddieruf** [comment]
My idea is to create an air-gapped branch that only has `pipeline.yml` and `vars-min.yml`. These will be augmented resource types and variables for getting needed things.

List of needed things and where I believe they could live on the network...
- ISO [vsphere datastore]
- This repo [internal git, like gitlab or git enterprise]
- Windows update server URL
- govc [downloadable place by concourse worker]
- stembuild [downloadable place by concourse worker]
- LGPO [downloadable place by concourse worker]
- vmware tools [downloadable place by concourse worker]
- windows update powershell [downloadable place by concourse worker]
- ubuntu docker image with dosfstools, mtools, xmlstarlet, jq [internal image registry]
- `concourse-curl-resource` docker image [internal image registry]

Changes to be made in **master** branch
- Optionally provide windows update server URL and add into unattended task to set reg value
- Add `windows-update-server-url` pipeline variable

Change to be made in **air-gapped** branch `pipeline.yml`
- Change `stembuild-release` pipeline resource type to file-url
- Change `govc` pipeline resource type to file-url
- Add `vmware-tools` pipeline resource as file-url
- Add `lgpo-url` pipeline variable for resource
- Add `windows-update-ps` pipeline resource as file-url
- Add `ubuntu-image-url` pipeline variable for resource
- Add `curl-image-url` pipeline variable for resource

Thoughts @sneal ?

**Comment by sneal** [comment]
@ddieruf It'd be better to support offline pipelines as first class citizens in the master branch as it's pretty common to have some limitations on internet access. We can probably add offline instructions to the readme from what you've started in this thread.

In addition to what you've mentioned we also have the apt-get installed dependencies to account for.

**Comment by sneal** [comment]
Ultimately replacing the cobbled together binaries, resources, and scripts with a single golang binary would make offline pipelines _much_ easier. Most of the xml processing, string replacement, and file downloading could easily be done via golang without external dependencies.

While I haven't looked at it I'm betting there's a way to replace the LGPO.exe with a golang lib that interacts with the Win32 API that stembuild or something else could use thus removing another dependency we can't redistribute.

**Comment by ddieruf** [comment]
I am working on access to https://hub.docker.com/u/cfcommunity. Looking to create an ubuntu image with all necessary binaries. This will clean things up a bit and give us something to distribute for offline pipelines.

**Comment by ddieruf** [comment]
With the docker image now listed, I've added direction for offline scenarios. @sneal and @tezizzm if you agree this fills the need I would like to close the issue.

**Comment by sneal** [comment]
@ddieruf Did you try running it offline?

**Comment by sneal** [comment]
Govc is Apache2 licensed so I believe we can include that in the base image. LGPO and Stembuild will have to come from Microsoft and Pivotal respectively.

I think we should remove the need to use `pivotalservices/concourse-curl-resource` by removing the resource and just `curl`'ing the file from the task. There's no _real_ benefit to treat that as a resource.

**Comment by ddieruf** [comment]
I like the portability of lgpo in the task. Then one can choose where it should come from. If it's curl'd within the task are you thinking of an option to provide the url or default to M$ site?

⁣
