### ISSUE TITLE
update process leaves vm in recover mode

### ISSUE THREAD

**Issue by bottkars** [cloudfoundry-community/windows-stemcell-concourse#23]
power off and reboot sequences used do not check tools state on power operations. this might leave vm´s with recover screen after cloning.

Working on Fix

**Comment by bottkars** [comment]
Example of base update workflow
![image](https://user-images.githubusercontent.com/8255007/68996984-84439580-08a1-11ea-8dcb-56efdcd22b0b.png)

**Comment by sneal** [comment]
Good catch. I haven't seen this personally but I was wondering if it could happen given that installs async.

**Comment by ddieruf** [comment]
This is fixed in the merged PR with @bottkars code.
