### ISSUE TITLE
2019.14 stembuild failing with windows server update enhancement

### ISSUE THREAD

**Issue by hmuthusamy** [cloudfoundry-community/windows-stemcell-concourse#27]
[2019.14 stembuild construct log.txt](https://github.com/cloudfoundry-community/windows-stemcell-concourse/files/3984039/2019.14.stembuild.construct.log.txt)

It looks like they added some new features as per the release notes related to root certs from windows updates server, but it seems to be failing on our environment. I have attached the log file. I have updated the OS Version to 2019.13 and it ran the construct and it completed fine. Let me know If I need to open a case to identify if this is potential issue with the stembuild or an environment issue. 2019.13 works fine. 

2019.14

Release Date: December 16, 2019

Features
Root certificates on machines deployed using stembuild-built stemcells get updated certificates from the Windows Updates Server

019-12-19T02:43:00.4212837+00:00 Loading certs from windows update server

The server name or address could not be resolved 0x80072ee7 (WinHttp: 12007 ERROR_WINHTTP_NAME_NOT_RESOLVED) -- http://ctldl.windowsupdate.com/msdownload/update/v3/static/trustedr/en/authrootstl.cab

CertUtil: -generateSSTFromWU command FAILED: 0x80072ee7 (WinHttp: 12007 ERROR_WINHTTP_NAME_NOT_RESOLVED)

CertUtil: The server name or address could not be resolved

2019-12-19T02:43:00.9682289+00:00 Error generating cert file from windows update server, exited with -2147012889

**Comment by ddieruf** [comment]
I just ran through this with the latest pipeline and didn't see the error. Do your concourse workers have internet access? Specifically microsoft.com?

**Comment by hmuthusamy** [comment]
Hi David
No. We are running on airgapped environment with no internet access. Alternate options?. if this a needed resource we might want to pull and store internally in our S3 buckets and then utilize from there instead.

**Comment by ddieruf** [comment]
Ok. This is motivation for me to document how to run in such an environment. Stay tuned.

**Comment by hmuthusamy** [comment]
Thanks @ddieruf . This has always been the challenge for us to adjust for the changes. For all the other resources in general like the LGPO we have a seperate pipeline to pull resources from internet and store seperately in s3 bucket or in harbor. We then pull from there in the stembuild pipeline. So if there is any external resources that are needed it would be great to have it as a resource. 

Also can you provide me the actual destination from microsoft from where the root server certs are downloded?

**Comment by ddieruf** [comment]
HI @hmuthusamy, I have added a new branch called "air-gapped" to the project. You can find all the documentation in the [wiki](https://github.com/cloudfoundry-community/windows-stemcell-concourse/wiki/Running-Offline).
