### ISSUE TITLE
base os install hags at "Wait for windows install to complete"

### ISSUE THREAD

**Issue by DonBower** [cloudfoundry-community/windows-stemcell-concourse#28]
While running the pipeline, the create-base task hangs waiting for OS Install to complete.
here are the Image Names available in my \sources\install.wim file:

1. Windows Server 2019 Standard
1. Windows Server 2019 Standard (Desktop Experience)
1. Windows Server 2019 Datacenter
1. Windows Server 2019 Standard (Desktop Experience)

I have tried both "Windows Server 2019 Standard" and "SERVERSTANDARDCORE".

What is the right value to use for:
operating-system-name: "SERVERSTANDARDCORE" #Used during the Windows installaton
vm-guest-os-id: 'windows9Server64Guest'
base-vm-name: "paswin-stemcell-base" #The name of the initial Windows VM created

**Comment by ddieruf** [comment]
Hi Don,
Apologies for the late answer. The value you want to use in vars yaml:

`operating-system-name: "Windows Server 2019 SERVERSTANDARDCORE"`

To discover what images are available in the ISO you are using refer to this doc - [https://docs.microsoft.com/en-us/windows-hardware/customize/desktop/unattend/microsoft-windows-setup-imageinstall-dataimage-installfrom-metadata](https://docs.microsoft.com/en-us/windows-hardware/customize/desktop/unattend/microsoft-windows-setup-imageinstall-dataimage-installfrom-metadata).

You will find the data image (.wim) file wihin the ISO. Extract it to a folder and then run the suggested command.

**Comment by DonBower** [comment]
LOL. I tried one, then the other, but not both at the same time!

**Comment by DonBower** [comment]
I was able to get past the previous issue.
I have created a pull request for the READ.ME to put the value in quotes, because on my computer, it appeared to be two separate values. and hopefully seeing the whole value in quotes will be more intuitive.
