### ISSUE TITLE
Windows vmware tools are not the latest ver by default

### ISSUE THREAD

**Issue by DonBower** [cloudfoundry-community/windows-stemcell-concourse#29]
The latest version is https://packages.vmware.com/tools/releases/latest/windows/x64/VMware-tools-11.0.5-15389592-x86_64.exe

but the default is https://packages.vmware.com/tools/releases/10.3.10/windows/x64/VMware-tools-10.3.10-12406962-x86_64.exe
which returns "toolsOld"

**Comment by DonBower** [comment]
there should be some scripting that retrieves the latest ver, or allows toolsOld.

**Comment by ddieruf** [comment]
Hi @DonBower. I got into this building the new air-gapped branch and [documenting it](https://github.com/cloudfoundry-community/windows-stemcell-concourse/wiki/Running-Offline). I am not sure that setting the pipeline to default to the latest tools is the right call. There is a strict compatibility between the vmware tools version with the version of ESXi running. [Here](https://packages.vmware.com/tools/versions) is a chart.

If the pipeline assumes the latest version of tools then it is also assuming the latest version of ESXi, and be both know that's never the case. I am now leaning toward removing the vmware tools URL altogether from the pipeline and make the var a required one.
