### ISSUE TITLE
stembuild job fails during Start construct step

### ISSUE THREAD

**Issue by DonBower** [cloudfoundry-community/windows-stemcell-concourse#30]
Initializing govc
true
--------------------------------------------------------
Verify LGPO
--------------------------------------------------------
Done
--------------------------------------------------------
Start the cloned VM
--------------------------------------------------------
Done
--------------------------------------------------------
Start construct
--------------------------------------------------------
/tmp/build/b012113a/stembuild/stembuild-linux-x86_64-2019.15 construct -vm-ip '<IP>' -vm-username 'administrator' -vm-password 'XXXXX' -vcenter-url 'XXXXXX' -vcenter-username 'XXXXX' -vcenter-password 'XXXXXX' -vm-inventory-path '/BBBBB/vm/AAAA/2019.15' -vcenter-ca-certs '/tmp/tmp.XcJDGxPiLq'

Validating connection to vm...Could not prepare VM: host 10.162.252.188 is unreachable. Please ensure WinRM is enabled and the IP is correct
[ERROR]: running construct

When attempting to RDP to the 2019.15 VM, I get this error:
We couldn't connect to the remote PC. Make sure the PC is turned on and connected to the network, and that remote access is enabled.

Error code: 0x204

**Comment by ddieruf** [comment]
Hi Don, I believe Shawn is going to set up a call with all of us together. Lets work through it.

**Comment by ddieruf** [comment]
Remote into the 2019.15 vm through vcenter console are run each of these:

`winrm set winrm/config/service/auth @{Basic="true"}`
`winrm set winrm/config/service @{AllowUnencrypted="true"}`
`Enable-NetFirewallRule -DisplayName "Windows Remote Management (HTTP-In)"`
`netsh firewall add portopening TCP 5985 "Port 5985"`

**Comment by amakhija** [comment]
Hi all, the link to the fix for this KB can be found [here](https://community.pivotal.io/s/article/Validating-connection-to-vm-step-fails-during-stembuild-construct-for-Stembuild-v2019-15)
