### ISSUE TITLE
Multiple YAML files have duplicate entries

### ISSUE THREAD

**Issue by jak74** [cloudfoundry-community/windows-stemcell-concourse#42]
The vmware_tools_status and timeout entries are duplicated in clone-base.yml (lines 24-25 and 27-28).  This causes issues with newer releases of yq:

failed to create task config from bytes pipeline-resources/tasks/clone-base.yml: error converting YAML to JSON: yams: unmarshal errors:
  line 27: key "vmware_tools_status" already set in map
  line 28: key "timeout" already set in map

The same is true of construct.yml, package.yml, and update-base.yml as well (in addition to clone-base.yml).

**Comment by sneal** [comment]
Looks like these were fixed in various PRs #47 #48 #50
