### ISSUE TITLE
duplicate keys on job clone-base

### ISSUE THREAD

**Issue by whizzer75** [cloudfoundry-community/windows-stemcell-concourse#47]
failed to create task config from bytes pipeline-resources/tasks/clone-base.yml: error converting YAML to JSON: yaml: unmarshal errors:
  line 27: key "vmware_tools_status" already set in map
  line 28: key "timeout" already set in map

**Comment by itgrl-bex** [comment]
Clone base job working now that the duplicate keys have been removed.

**Comment by sneal** [comment]
Fixed by #48
